### ISSUE TITLE
node.js 5.11.0: Could not find formatter 'stylish'

### ISSUE THREAD

**Issue by papandreou** [One-com/eslint-config-onelint-react#9]
https://travis-ci.org/assetgraph/assetgraph/jobs/126035656

Any idea, @gustavnikolaj?

**Comment by gustavnikolaj** [comment]
Issue moved to [One-com/eslint-config-onelint #24](https://github.com/One-com/eslint-config-onelint/issues/24) via [**ZenHub.io**](https://www.zenhub.io/)
